language: node_js

node_js:
  - "0.10"

before_install:
  # Install selenium-server-standalone
  - wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar
  - export SELENIUM=`pwd`/selenium-server-standalone-2.43.1.jar

before_script:
  # Install BrowserStackLocal
  - wget https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
  - unzip BrowserStackLocal-linux-x64.zip
  - mv BrowserStackLocal bin
  # Update to your BrowserStack account information
  - cp browserstack-conf.example.json browserstack-conf.json
  - bin/BrowserStackLocal WX9Py47as45EL12ttsJx localhost,3001,0 > /dev/null &
  - sleep 5

script:
  - mocha test/minimum-e2e.js
